- src/branch_builder/provision_branch_builder.cpp
- src/initializing/sakura_compiler.cpp
- src/initializing/sakura_compiler.h
- src/items/sakura_items.cpp
- src/items/sakura_items.h
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- tests/test_dir/branches/branch.sb
introduced new blossom-group as additional abstraction-layer
#5 
With a simple branch-only example:
```
[install_branch]
- packages = nano
apt(apt_blossomX)
-> update
-> present:
-names = "{{packages}}"
```
> Fix blossom subtypes

- src/common/defines.h
- src/initializing/sakura_compiler.cpp
- src/items/item_methods.cpp
- src/items/sakura_items.h
- src/processing/process_methods.cpp
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
Fixed output of the blossoms to also show the name of the current branch and trees.
close #17 
Normal example without debug-output
> fixed hierarchy-output in blossom-output

- src/branch_builder/provision_branch_builder.cpp
- src/common/includes.h
- src/initializing/file_collector.cpp
- src/initializing/file_collector.h
- src/initializing/sakura_compiler.cpp
- src/initializing/sakura_compiler.h
- src/items/item_methods.cpp
- src/items/item_methods.h
- src/items/sakura_items.cpp
- src/items/sakura_items.h
- src/processing/blossoms/blossom.cpp
- src/processing/blossoms/install/apt/apt_absent_blossom.cpp
- src/processing/blossoms/install/apt/apt_latest_bossom.cpp
- src/processing/blossoms/install/apt/apt_methods.cpp
- src/processing/blossoms/install/apt/apt_present_bossom.cpp
- src/processing/blossoms/sakura/sakura_copy_subtree_blossom.cpp
- src/processing/blossoms/ssh/ssh_cmd_blossom.cpp
- src/processing/blossoms/ssh/ssh_cmd_create_file_blossom.cpp
- src/processing/blossoms/ssh/ssh_scp_blossom.cpp
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- src/sakura_root.cpp
- tests/core/common_methods_test.cpp
replaced data-item-tree, which comes from the sakura-parser with json-items, to make handling easier and the code cleaner.
close #19 
simple example execution
> replaced data-items by json-items

- src/initializing/sakura_compiler.cpp
- src/initializing/sakura_compiler.h
- src/items/sakura_items.h
- src/processing/blossoms/install/apt/apt_methods.cpp
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- tests/test_dir/branches/branch.sb
add if-else-conditions to branches (only equal and unequal)
close #14 
updated branch-testfile
> Add if condition

- SakuraTree.pro
- build.sh
- src/branch_builder/provision_branch_builder.cpp
- src/initializing/sakura_compiler.cpp
- src/initializing/sakura_compiler.h
- src/items/item_methods.cpp
- src/items/sakura_items.h
- src/processing/blossoms/blossom.cpp
- src/processing/blossoms/blossom_getter.cpp
- src/processing/blossoms/install/apt/apt_absent_blossom.cpp
- src/processing/blossoms/install/apt/apt_latest_bossom.cpp
- src/processing/blossoms/install/apt/apt_methods.cpp
- src/processing/blossoms/install/apt/apt_present_bossom.cpp
- src/processing/blossoms/sakura/print_blossom.cpp
- src/processing/blossoms/sakura/print_blossom.h
- src/processing/blossoms/ssh/ssh_cmd_blossom.cpp
- src/processing/blossoms/ssh/ssh_cmd_create_file_blossom.cpp
- src/processing/blossoms/ssh/ssh_scp_blossom.cpp
- src/processing/process_methods.cpp
- src/sakura_root.cpp
- tests/test_dir/branches/branch.sb
- added print-blossom
- updated blossom-groups to be handled without blossom
- #27 
updated test-file
> add print-method

- SakuraTree.pro
- src/branch_builder/provision_branch_builder.cpp
- src/initializing/sakura_compiler.cpp
- src/initializing/sakura_compiler.h
- src/items/item_methods.cpp
- src/items/item_methods.h
- src/items/sakura_items.cpp
- src/items/sakura_items.h
- src/processing/blossoms/blossom.cpp
- src/processing/blossoms/install/apt/apt_absent_blossom.cpp
- src/processing/blossoms/install/apt/apt_latest_bossom.cpp
- src/processing/blossoms/install/apt/apt_methods.cpp
- src/processing/blossoms/install/apt/apt_present_bossom.cpp
- src/processing/blossoms/install/apt/apt_update_blossom.cpp
- src/processing/blossoms/install/apt/apt_upgrade_blossom.cpp
- src/processing/blossoms/sakura/print_blossom.cpp
- src/processing/blossoms/sakura/sakura_copy_subtree_blossom.cpp
- src/processing/blossoms/ssh/ssh_cmd_blossom.cpp
- src/processing/blossoms/ssh/ssh_cmd_create_file_blossom.cpp
- src/processing/blossoms/ssh/ssh_scp_blossom.cpp
- src/processing/process_execution.cpp
- src/processing/process_execution.h
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- src/sakura_root.cpp
- tests/test_dir/branches/branch.sb
Update syntax to store blossom-output into a value
- #27
- updated test-file
> add possibility to store blossom-output in value

- src/initializing/sakura_compiler.cpp
- src/initializing/sakura_compiler.h
- src/sakura_root.cpp
remove code duplications for the compiler-call
#7 
- normal example test
> cleanup compiler-call

- src/branch_builder/provision_branch_builder.cpp
- src/common/defines.h
- src/items/sakura_items.cpp
- src/items/sakura_items.h
- src/processing/blossoms/blossom.cpp
- src/processing/blossoms/files/common_files/file_copy_blossom.cpp
- src/processing/blossoms/files/common_files/file_delete_blossom.cpp
- src/processing/blossoms/files/common_files/file_rename_blossom.cpp
- src/processing/blossoms/install/apt/apt_absent_blossom.cpp
- src/processing/blossoms/install/apt/apt_latest_bossom.cpp
- src/processing/blossoms/install/apt/apt_methods.cpp
- src/processing/blossoms/install/apt/apt_present_bossom.cpp
- src/processing/blossoms/sakura/print_blossom.cpp
- src/processing/blossoms/sakura/sakura_copy_subtree_blossom.cpp
- src/processing/blossoms/ssh/ssh_cmd_blossom.cpp
- src/processing/blossoms/ssh/ssh_cmd_create_file_blossom.cpp
- src/processing/blossoms/ssh/ssh_scp_blossom.cpp
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- src/sakura_compiler.cpp
- tests/processing/blossoms/files/common_files/file_copy_blossom_test.cpp
- tests/processing/blossoms/files/common_files/file_delete_blossom_test.cpp
- tests/processing/blossoms/files/common_files/file_rename_blossom_test.cpp
removed some pointers to make code cleaner
- unit-tests
> removed some pointer

- SakuraTree.pro
- src/processing/blossoms/blossom_getter.cpp
- src/processing/blossoms/install/apt/apt_latest_bossom.cpp
- src/processing/blossoms/install/apt/apt_present_bossom.cpp
- src/processing/blossoms/special/cmd_blossom.cpp
- src/processing/blossoms/special/cmd_blossom.h
- src/processing/blossoms/special/print_blossom.cpp
- tests/processing/blossoms/special/cmd_blossom_test.cpp
- tests/processing/blossoms/special/cmd_blossom_test.h
- tests/run_unit_tests.cpp
Add cmd blossom
close #38 
- added new unit-tests
> Add cmd blossom

- src/sakura_compiler.cpp
update compiler for the new item-representaion
#40 
- current example
> update compiler for the new item-representaion

- examples/branches/branch.sb
- src/items/sakura_items.h
- src/processing/blossoms/blossom.cpp
- src/processing/sakura_thread.cpp
- src/sakura_compiler.cpp
connect new output-syntax for blossoms
#42 
- not tested now
> connect new output-syntax for blossoms

- README.md
- SakuraTree.pro
- examples/branches/branch.sb
- src/processing/blossoms/blossom_getter.cpp
- src/processing/blossoms/special/assert_blossom.cpp
- src/processing/blossoms/special/assert_blossom.h
- src/sakura_compiler.cpp
Add assert-blossom to check value-contents
- #16 
- tested with updated example
> Add assert blossom

- README.md
- examples/branches/branch.sb
- src/items/item_methods.cpp
- src/items/item_methods.h
- src/items/value_items.h
- src/processing/sakura_thread.cpp
- src/sakura_compiler.cpp
- src/sakura_compiler.h
Use the rework of #56 to also use identifier and not only jinja2-strings to insert values in functions.
- close #59 
- unit-tests
> Improve value processing

- README.md
- examples/branches/branch.sb
- src/items/sakura_items.cpp
- src/items/sakura_items.h
- src/items/value_items.h
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- src/sakura_compiler.cpp
- src/sakura_compiler.h
added for-each-loops.
- #15 
- tested with updated example
> Add for loops

- README.md
- SakuraTree.pro
- examples/branches/branch.sb
- src/common/defines.h
- src/items/item_methods.cpp
- src/items/sakura_items.cpp
- src/items/sakura_items.h
- src/items/value_item_functions.cpp
- src/items/value_item_functions.h
- src/items/value_items.h
- src/processing/sakura_thread.cpp
- src/sakura_compiler.cpp
- tests/items/value_items_functions_test.cpp
- tests/items/value_items_functions_test.h
- tests/run_unit_tests.cpp
Add commen used methods
- close #55 
- new unit-tests
> Add common used methods

- README.md
- SakuraTree.pro
- build.sh
- examples/branches/branch.sb
- examples/branches/files/test_file
- src/items/item_methods.cpp
- src/processing/blossoms/blossom_getter.cpp
- src/processing/blossoms/files/common_files/file_copy_blossom.cpp
- src/processing/blossoms/files/common_files/file_rename_blossom.cpp
- src/processing/blossoms/files/file_methods.cpp
- src/processing/blossoms/files/file_methods.h
- src/processing/blossoms/files/ini_files/ini_delete_entry_blossom.cpp
- src/processing/blossoms/files/ini_files/ini_delete_entry_blossom.h
- src/processing/blossoms/files/ini_files/ini_read_entry_blossom.cpp
- src/processing/blossoms/files/ini_files/ini_read_entry_blossom.h
- src/processing/blossoms/files/ini_files/ini_set_entry_blossom.cpp
- src/processing/blossoms/files/ini_files/ini_set_entry_blossom.h
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- tests/items/item_methods_test.cpp
- tests/processing/blossoms/files/common_files/file_copy_blossom_test.cpp
- tests/processing/blossoms/files/file_methods_test.cpp
added ini-file-blossoms
- #45 
> Add ini file blossom

- src/processing/blossoms/files/common_files/file_chmod_blossom.cpp
- src/processing/blossoms/files/common_files/file_chmod_blossom.h
- src/processing/blossoms/files/common_files/file_chown_blossom.cpp
- src/processing/blossoms/files/common_files/file_chown_blossom.h
added content to chmod-blossom and chown-blossom
- #10 
- not tested now
> filled file-chown and file-chmow blossoms

- src/common/typedefs.h
- src/items/item_methods.cpp
- src/items/item_methods.h
- src/items/sakura_items.cpp
- src/items/sakura_items.h
- src/processing/blossoms/files/common_files/file_copy_blossom.cpp
- src/processing/blossoms/files/common_files/file_rename_blossom.cpp
- src/processing/blossoms/files/file_methods.cpp
- src/processing/blossoms/files/file_methods.h
- src/processing/blossoms/files/ini_files/ini_delete_entry_blossom.cpp
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- src/sakura_compiler.cpp
- src/sakura_compiler.h
- tests/items/item_methods_test.cpp
- tests/processing/blossoms/files/file_methods_test.cpp
cleanup-phase
- #47 
- example
- unit-tests
> Cleanup phase

- .gitlab-ci.yml
- README.md
- SakuraTree.pro
- build.sh
- src/sakura_root.cpp
removed some unused requirements and made some fixes in the build-script
- unit-tests
- example
> Cleanup build process

- README.md
- examples/branches/branch.sb
- src/items/value_item_functions.cpp
- src/processing/sakura_thread.cpp
- tests/items/value_items_functions_test.cpp
Updated contains-method to also check array and values.
- close #70 
- updated unit-tests
> Update contains method

- README.md
- examples/branches/branch.sb
- src/items/sakura_items.cpp
- src/items/sakura_items.h
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- src/sakura_compiler.cpp
- src/sakura_compiler.h
added parallel for-loops
- close #72 
- close #66 
> Add parallel processing to branches

- examples/branches/branch.sb
- src/processing/blossoms/special/cmd_blossom.cpp
- src/processing/sakura_thread.cpp
some fixes
- close #74 
- unit-tests
> Fix cmd blossom

- examples/branches/branch.sb
- src/items/sakura_items.cpp
- src/items/sakura_items.h
- src/processing/blossoms/special/assert_blossom.cpp
- src/processing/sakura_thread.cpp
fix assert-blossom
- close #82 
> fix assert-blossom

- src/common/typedefs.h
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- src/processing/subtree_queue.h
- src/sakura_root.cpp
Threads, which are spawning tasks into separate threads, are now waiting
until the tasks are finished.
- #85 
- example
> fixed multi-threading

- SakuraTree.pro
- examples/branches/branch.sb
- src/converter.cpp
- src/converter.h
- src/main.cpp
- src/processing/sakura_thread.cpp
- src/sakura_root.cpp
- src/sakura_root.h
add input-values via arguments
- close #87 
- manually tested
> add input-values via arguments and renamed compiler-class to converter

- SakuraTree.pro
- examples/branches/branch.sb
- src/processing/blossoms/blossom_getter.cpp
- src/processing/blossoms/special/exit_blossom.cpp
- src/processing/blossoms/special/exit_blossom.h
add exit-blossom
- close #91 
- simple example-test
> add exit-blossom

- src/converter.cpp
- src/converter.h
- src/items/item_methods.cpp
- src/items/item_methods.h
- src/items/value_items.h
- src/processing/sakura_thread.cpp
- src/sakura_root.cpp
- src/sakura_root.h
- tests/items/item_methods_test.cpp
Update stability of value handling
- #78 
- #79 
- manually tests with example
> Update stability of value handling

- SakuraTree.pro
- examples/example.tree
- src/processing/blossoms/blossom_getter.cpp
- src/processing/blossoms/files/common_files/path_chmod_blossom.cpp
- src/processing/blossoms/files/common_files/path_chmod_blossom.h
- src/processing/blossoms/files/common_files/path_chown_blossom.cpp
- src/processing/blossoms/files/common_files/path_chown_blossom.h
- src/processing/blossoms/files/common_files/path_copy_blossom.cpp
- src/processing/blossoms/files/common_files/path_copy_blossom.h
- src/processing/blossoms/files/common_files/path_delete_blossom.cpp
- src/processing/blossoms/files/common_files/path_delete_blossom.h
- src/processing/blossoms/files/common_files/path_rename_blossom.cpp
- src/processing/blossoms/files/common_files/path_rename_blossom.h
- src/processing/blossoms/ssh/ssh_cmd_create_file_blossom.h
- tests/processing/blossoms/files/common_files/path_chmod_blossom_test.cpp
- tests/processing/blossoms/files/common_files/path_chmod_blossom_test.h
- tests/processing/blossoms/files/common_files/path_chown_blossom_test.cpp
- tests/processing/blossoms/files/common_files/path_chown_blossom_test.h
- tests/processing/blossoms/files/common_files/path_copy_blossom_test.cpp
- tests/processing/blossoms/files/common_files/path_copy_blossom_test.h
- tests/processing/blossoms/files/common_files/path_delete_blossom_test.cpp
- tests/processing/blossoms/files/common_files/path_delete_blossom_test.h
- tests/processing/blossoms/files/common_files/path_rename_blossom_test.cpp
- tests/processing/blossoms/files/common_files/path_rename_blossom_test.h
- tests/run_unit_tests.cpp
renamed file-blossoms to path-blossoms to be more generic
- close #104 
- example test
> renamed file-blossoms to path-blossoms to be more generic

- README.md
- examples/example.tree
- src/main.cpp
- src/processing/blossoms/files/common_files/path_chmod_blossom.cpp
- src/processing/blossoms/files/common_files/path_chmod_blossom.h
- src/processing/blossoms/files/common_files/path_chown_blossom.cpp
- src/processing/blossoms/files/common_files/path_chown_blossom.h
- src/processing/blossoms/files/common_files/path_delete_blossom.cpp
- src/processing/blossoms/files/common_files/path_delete_blossom.h
- src/processing/blossoms/files/common_files/path_rename_blossom.cpp
- src/processing/blossoms/files/common_files/path_rename_blossom.h
- src/processing/blossoms/files/ini_files/ini_delete_entry_blossom.cpp
- src/processing/blossoms/files/text_files/text_append_blossom.cpp
- src/processing/blossoms/files/text_files/text_write_blossom.cpp
- src/processing/common/item_methods.cpp
- src/processing/sakura_thread.cpp
- src/sakura_root.cpp
- tests/processing/blossoms/files/common_files/path_delete_blossom_test.cpp
- tests/processing/blossoms/files/common_files/path_rename_blossom_test.cpp
- tests/processing/blossoms/files/text_files/text_append_blossom_test.cpp
- tests/processing/blossoms/files/text_files/text_write_blossom_test.cpp
While writing the documentation, some bugs were still found in the code.
#50 
- unit tests and smaller examples
> Little fixes and changes

- examples/example.tree
- src/processing/sakura_thread.cpp
blossom-group names can now be jinja2-strings
- close #116 
> changed names of blossoms-groups to jinja2-string

- examples/example.tree
- src/converter/converter.cpp
- src/processing/common/item_methods.cpp
- src/processing/common/value_item_functions.cpp
- src/processing/common/value_item_functions.h
- src/processing/sakura_thread.cpp
update for map-input
- add capability to directly define map and assign them to items
- fixed insert-function
- fixed error-case for functions in general
- update example
- #117 
> update for map-input

- SakuraTree.pro
- src/processing/blossoms/blossom_getter.cpp
- src/processing/blossoms/special/assert_blossom.cpp
- src/processing/blossoms/special/item_update_blossom.cpp
- src/processing/blossoms/special/item_update_blossom.h
Added blossom to update existing parent-items, for example to override
the item completely or appent items to an array-item.
- #115 
- example-test
> add item_update-blossom

- examples/example.tree
- src/common/defines.h
- src/processing/common/item_methods.cpp
- src/processing/common/item_methods.h
- src/processing/common/value_item_functions.cpp
- src/processing/common/value_item_functions.h
- src/processing/sakura_thread.cpp
- tests/processing/common/functions_test.cpp
- tests/processing/common/item_methods_test.cpp
functions have now its own specific error-messages for easier debugging
- #121 
- unit-tests
- example-test
> functions have now its own specific error-messages

- .gitlab-ci.yml
- README.md
- SakuraTree.pro
- build.sh
- src/args.h
- src/main.cpp
Replace the argument-parser of the boost library with my own parser.
- #135 
- only build-test
> replace argument-parser

- .gitignore
- examples/trees/example.tree
- src/args.h
- src/main.cpp
- src/processing/blossoms/files/common_files/path_chmod_blossom.cpp
- src/processing/blossoms/files/common_files/path_chown_blossom.cpp
- src/processing/blossoms/install/apt/apt_absent_blossom.cpp
- src/processing/blossoms/install/apt/apt_latest_bossom.cpp
- src/processing/blossoms/install/apt/apt_methods.cpp
- src/processing/blossoms/install/apt/apt_present_bossom.cpp
- src/processing/blossoms/install/apt/apt_update_blossom.cpp
- src/processing/blossoms/install/apt/apt_upgrade_blossom.cpp
- src/processing/blossoms/special/cmd_blossom.cpp
- src/processing/blossoms/ssh/ssh_cmd_blossom.cpp
- src/processing/blossoms/ssh/ssh_cmd_create_file_blossom.cpp
- src/processing/blossoms/ssh/ssh_scp_blossom.cpp
Add debug flag `--debug` and `-d` to the cli
- #141 
- example-test with and without `-d` flag
> Add debug flag

- src/processing/blossoms/special/cmd_blossom.cpp
- src/processing/blossoms/special/cmd_blossom.h
- src/processing/common/item_methods.cpp
- Add trim function to cmd blossom
- example-test
> Add trim function to cmd blossom

- README.md
> add syntax-example to readme

- SakuraTree.pro
- build.sh
- examples/example.seed
- src/args.h
- src/common/includes.h
- src/config.h
- src/main.cpp
- src/predefined_subtrees/sakura_provisioning_subtree.tree
- src/processing/blossoms/ssh/ssh_cmd_blossom.cpp
- src/processing/blossoms/ssh/ssh_cmd_create_file_blossom.cpp
- src/processing/blossoms/ssh/ssh_scp_blossom.cpp
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- src/processing/sakura_tree_callbacks.h
- src/sakura_root.cpp
- src/sakura_root.h
- src/tree_handler.cpp
- src/tree_handler.h
- rework seed-processing
- add sharing of templates and files
- update predefined ssh-provisioning tree
- #154 
- (will be tested with the second part)
> Fix multinode feature

- build.sh
- src/main.cpp
- src/processing/blossoms/files/common_files/path_copy_blossom.cpp
- src/processing/blossoms/files/template_files/template_create_file_blossom.cpp
- src/processing/blossoms/files/template_files/template_create_string_blossom.cpp
- src/sakura_root.cpp
- src/sakura_root.h
- change input to only allow files and no tree-ids anymore
- #162 
- examples within the repo
> Problems with templates when selecting only a single tree

- src/common/includes.h
- src/main.cpp
- src/processing/blossoms/files/common_files/path_chmod_blossom.cpp
- src/processing/blossoms/files/common_files/path_chown_blossom.cpp
- src/processing/blossoms/files/common_files/path_copy_blossom.cpp
- src/processing/blossoms/files/common_files/path_delete_blossom.cpp
- src/processing/blossoms/files/common_files/path_rename_blossom.cpp
- src/processing/blossoms/files/ini_files/ini_delete_entry_blossom.cpp
- src/processing/blossoms/files/ini_files/ini_read_entry_blossom.cpp
- src/processing/blossoms/files/ini_files/ini_set_entry_blossom.cpp
- src/processing/blossoms/files/template_files/template_create_file_blossom.cpp
- src/processing/blossoms/files/template_files/template_create_string_blossom.cpp
- src/processing/blossoms/files/text_files/text_append_blossom.cpp
- src/processing/blossoms/files/text_files/text_read_blossom.cpp
- src/processing/blossoms/files/text_files/text_replace_blossom.cpp
- src/processing/sakura_thread.cpp
- src/processing/sakura_tree_callbacks.h
- src/sakura_root.cpp
- tests/processing/blossoms/special/cmd_blossom_test.cpp
- update for current version of libKitsunemimiPersistence
> update for current version of libKitsunemimiPersistence

- SakuraTree.pro
- src/common/includes.h
- src/processing/blossoms/files/template_files/template_create_file_blossom.cpp
- src/processing/blossoms/files/template_files/template_create_string_blossom.cpp
- src/processing/sakura_thread.cpp
- src/processing/validator.cpp
- src/processing/validator.h
- src/sakura_root.cpp
- src/sakura_root.h
Add new blossom-validator for simple requirements-check of the blossoms
- #151 
- tested with the template-tests in the examples
> Add blossom validator

- src/args.h
- src/main.cpp
- src/sakura_root.cpp
Allow relative path as cli-input.
- #100 
- manually test by calling with relative and absolute path
> Allow relative input path

- src/processing/common/item_methods.cpp
- src/processing/common/item_methods.h
- src/sakura_root.cpp
add item-check to check input-values against the initial tree
- #131 
- manually example-test with valid and invalid input
> add item-check to check input-values against the initial tree

- src/processing/blossoms/blossom.cpp
- src/processing/blossoms/blossom.h
- src/processing/common/item_methods.cpp
- src/processing/common/item_methods.h
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- src/processing/subtree_queue.h
- src/processing/validator.cpp
- src/processing/validator.h
- src/sakura_root.cpp
- src/sakura_root.h
Reworked error-message forwading to make this possible. Also fixed loops and parallel-loops itself.
- #152 
example-file:
```
["test templates"]
- converted_output = ""
- test_input = "new test-template"
parallel_for(i = 0; i < 1000; i++)
{
if(i == 100)
{
template("fail")
- source_path = "test_template.j2"
-> create_string:
- variables = { - checkner = 42
- name = test_input }
- blossom_output >> converted_output
}
else
{
template("create a template {{i}}")
- source_path = "test_template.j2"
-> create_string:
- variables = { - checker = 42
- name = test_input }
- blossom_output >> converted_output
}
}
```
output at the end:
```
...
=======================================================================================================
TREE: test templates
BLOSSOM: create a template 103 …
```
> Error does not break parallel loop

- src/processing/sakura_thread.cpp
rename tree-files into sakura-files
- https://github.com/tobiasanker/SakuraTree/issues/170
> rename tree-files into sakura-files

- examples/ressources-test/next/test.sakura
- examples/ressources-test/ressources/print_hostname.sakura
- examples/ressources-test/root.sakura
- src/processing/sakura_thread.cpp
- src/processing/sakura_thread.h
- src/processing/validator.cpp
add new ressource-processing
- #174 
- added new example for the testing of the new feature
> Add ressource directory

- src/args.h
- src/main.cpp
- src/sakura_root.cpp
- src/sakura_root.h
add dry-run feature to test without execution
- #180 
- manually test
> add dry-run feature to test without execution

- src/common/defines.h
- src/sakura_root.cpp
add logo at the beginning of a run
- #187 
- manually test
> add logo at the beginning of a run

- .github/ISSUE_TEMPLATE/tag_request_issue_template.md
- .gitlab-ci.yml
- README.md
- SakuraTree.pro
- build.sh
- src/common/includes.h
- src/processing/common/item_methods.cpp
- src/processing/sakura_thread.cpp
- src/processing/sakura_tree_callbacks.h
- src/sakura_root.cpp
Resources broken for multiple calls and update ci-runner.
- #185
> Ressources broken for multiple calls

- CHANGELOG
- README.md
updates for tagging feature-freeze 0.3.0ff
- #192 
- ci-pipeline
> updates for tagging feature-freeze 0.3.0ff

- src/blossoms/apt_blossoms.cpp
- src/blossoms/ini_blossoms.cpp
- src/blossoms/path_blossoms.cpp
- src/blossoms/speacal_blossom.cpp
- src/blossoms/ssh_blossoms.cpp
- src/blossoms/template_blossoms.cpp
- src/blossoms/text_blossoms.cpp
- src/common/includes.h
- tests/functional_tests/template-test/root.sakura
update for new blossom-validation
- https://github.com/kitsudaiki/libKitsunemimiSakuraLang/issues/74
- ci-pipeline
> update for new blossom-validation
